server:
  servlet:
    contextPath: /authorization
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.180:30010/oauth2_db
    username: oauth2
    password: oauth2
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false

signing:
  key: ass-oauth2

token:
  accessTime: 5000